version: "3"
services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      - POSTGRES_PASSWORD=senha123
    networks:
      mynetwork:
        ipv4_address: 172.20.0.10
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
