all:
	# Make sure you are inside "dagster-dtwy" virtual environment with "pyenv activate dagster-dtwy".
	clear;
	dagster dev -h 0.0.0.0 -p 3000

dependencies:
	clear;
	pip install pandas matplotlib seaborn scikit-learn